### ISSUE TITLE
SprayWebSockets chatrooms

### ISSUE THREAD

**Issue by troypayne** [lihaoyi/SprayWebSockets#15]
I'm attempting to create chat-rooms, using Something like this:

``` scala
class ChatService extends Actor with ChatMarshaller {
    val mediator = DistributedPubSubExtension(context.system).mediator
    def receive = {
        case x: Tcp.Connected => sender ! Register(self)
        case req: HttpRequest => sender ! Sockets.UpgradeServer(Sockets.acceptAllFunction(req), self)
        case Sockets.Upgraded => mediator ! Subscribe("mychatroom", sender)
        case f @ Frame(fin, rsv, Text, maskingKey, data) => {
            mediator ! Publish("mychatroom", Frame(opcode = OpCode.Text, data = ByteString(f.stringData)))
        }
    }
}
```

as you can see, I'm subscribing the sender to "mychatroom," and I'm also using the DistributedPubSubExtension mediator to to publish the message to all subscribers of "mychatroom"

The problem I'm having is, I'd like to create a unique key for "mychatroom" that's passed in from the request, but I'm not sure how to do that with the example above.

Any ideas?

**Comment by lihaoyi** [comment]
Hey, sorry for the delay.

I have no idea what a `DistributedPubSubExtension` is =(

You could pass in data through the incoming `req: HttpRequest`, which the `ChatService` actor could then use to decide what chat room this connection belongs to, and which chat room's messages should be send to it over websockets.

Would that do what you want?
