### ISSUE TITLE
won't compile against spray 1.2-RC2

### ISSUE THREAD

**Issue by weihsiu** [lihaoyi/SprayWebSockets#2]
i tried to compile the source against spray 1.2-RC2 but was not successful. apparently there were quite a few changes from spray 1.2-M8 which spraywebsockets was compiled against originally.  do you have any plan on updating it to be compatible with 1.2-RC2?

**Comment by lihaoyi** [comment]
Yeah, i plan on keeping it up to date and hopefully merging it into spray.io/akka.http at some point when it's stable. Currently spray is still in flux no don't see the point in tracking master till it lands

**Comment by lihaoyi** [comment]
I have updated it to work against spray 1.2-RC3 as of 70f9122e05b58b50c61627d2203b1383caa7fe2d

It's still lacking some stuff around backpressure support, by AFAIK the spray/akka people are still trying to sort that out internally, so no real good solution there.

Try it out and let me know if you have any problems with it!

**Comment by weihsiu** [comment]
thanks for the work but unfortunately i was in a hurry and had to use
unfiltered-websocket instead even though my entire stack is akka based.  i
will try spray-websocket when i have time.  thanks!

On Mon, Nov 18, 2013 at 1:31 AM, Li Haoyi notifications@github.com wrote:

> I have updated it to work against spray 1.2-RC3 as of 70f9122https://github.com/lihaoyi/SprayWebSockets/commit/70f9122e05b58b50c61627d2203b1383caa7fe2d
> 
> It's still lacking some stuff around backpressure support, by AFAIK the
> spray/akka people are still trying to sort that out internally, so no real
> good solution there.
> 
> Try it out and let me know if you have any problems with it!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lihaoyi/SprayWebSockets/issues/2#issuecomment-28654778
> .

## 

.......__o
.......<,
....( )/ ( )...
