### ISSUE TITLE
Command pipeline drops UpgradeServer

### ISSUE THREAD

**Issue by magnusart** [lihaoyi/SprayWebSockets#4]
Hi I'm trying to use spray websockets. When issuing the upgrade message I get the following warning message:

[SocketsSystem-akka.actor.default-dispatcher-2] [akka://SocketsSystem/user/IO-HTTP/listener-0/1] command pipeline: dropped spray.can.server.websockets.Sockets$UpgradeServer@3bc932f2

Then I get a timed out message shortly afterwards.

The case match looks like this

```
case req @ HttpRequest(
      HttpMethods.GET,
      Uri( _, _, Uri.Path( "/sockets" ), _, _ ),
      headers, _, _ ) ⇒
      sender ! Sockets.UpgradeServer(
        Sockets.acceptAllFunction( req ),
        publisherActor( genNewId() )
      )
```

Any suggestions? It looks like the warning message is from here: https://github.com/spray/spray/blob/master/spray-io/src/main/scala/spray/io/ConnectionHandler.scala#L31

**Comment by lihaoyi** [comment]
Two things:
- Can you give a self-contained example app that demonstrates this?
- Another thing: do the unit tests work for you?

Not sure what's wrong with it, but both of these things will help pinpoint the problem =)

**Comment by magnusart** [comment]
Hi

I can't easily get a self contained app on a short notice but I got a bit more code with output and some information about my nginx-setup.

The unit tests works if I build SprayWebSockets locally.

Code is here: https://gist.github.com/magnusart/78c60619fb4b06924484

By the way, do you know of any self contained example that uses SprayWebSockets together with a browser client? The provided examples are all Scala code.

**Comment by lihaoyi** [comment]
[src/test/scala/spray/can/server/websockets/SocketExample.scala](https://github.com/lihaoyi/SprayWebSockets/blob/master/src/test/scala/spray/can/server/websockets/SocketExample.scala) is a self-contained example that starts a socket echo server and a socket client on `localhost:12345` and checks that a ping-pong works before exiting. You can add a `Thread.sleep(1000000)` at the end of the test to make it not-exit, and then go to http://www.websocket.org/echo.html and try connecting and sending messages to `localhost:12345`. The messages should be echoed with everything capitalized.

**Comment by lihaoyi** [comment]
I'm going to close this issue for now; if the unit tests work, that means you probably set up something wrongly, but I don't really have time right now to go through your code and figure out what. You'll have to work backwards from a working state (e.g. the unit tests, or the example, or the autobahn tests...) to see where exactly you're going wrong =)

Sorry I wasn't more help!
