### ISSUE TITLE
Is it possible to multiplex with other actor?

### ISSUE THREAD

**Issue by BYVoid** [lihaoyi/SprayWebSockets#5]
Hi,

I really love your project. Nice job!

I have already an website based on `spray.routing.HttpService` and now I want to extend some parts of it with Websocket. Is SprayWebSockets possible to multiplex the same port of an existing actor? For example, dispatch all requests with path of `/websocket` to SprayWebSockets and remain other paths.

Thanks

**Comment by lihaoyi** [comment]
It's not able to multiplex with an existing actor that way, unfortunately. I don't think it's possible from the way spray/akka.io is architected now.

What you can do is run the Spray websocket server, and forward the non-websocket Http requests to your `spray.routing.HttpService`. I'm not sure what the api for that thing is, but I'd be surprised if this was particularly difficult. Give it a shot and let me know if the solution doesn't work =)

**Comment by BYVoid** [comment]
Thanks

**Comment by lihaoyi** [comment]
Closing this for now, feel free to re-open if there are still problems.
