### ISSUE TITLE
AckEventWithReceiver drop

### ISSUE THREAD

**Issue by okapies** [lihaoyi/SprayWebSockets#7]
The following log is shown when I send `Sockets.UpgradeServer(Sockets.acceptAllFunction(req), self)` to `sender`. I have experienced this issue when run `SocketServer` in [SocketExample](https://github.com/lihaoyi/SprayWebSockets/blob/395aae3d0440d107941c98fda434816a9424107a/src/test/scala/spray/can/server/websockets/SocketExample.scala#L33).

```
[WARN] [02/11/2014 02:04:17.685] [example-akka.actor.default-dispatcher-2] [akka
://example/user/IO-SOCKET/listener-0/0] event pipeline: dropped AckEventWithRece
iver(NoAck(null),HttpResponse(101 Switching Protocols,Empty,List(Upgrade: websoc
ket, Connection: Upgrade, Sec-WebSocket-Accept: ???),HTTP/1.1),Actor[akka://exam
ple/user/server#-1103739125])
```

**Comment by lihaoyi** [comment]
I've seen this, it's basically [this guy](https://github.com/lihaoyi/SprayWebSockets/blob/master/src/main/scala/spray/can/server/websockets/SocketPhases.scala#L64-L90) now handling/forwarding acks properly, so they get dropped and that message pops up. It's harmless, but if you want to make it go ahead, you can patch that class to make it do something sensible (probably just swallow them and keep quiet) and send me a PR =)

**Comment by lihaoyi** [comment]
0=[]=====> LGTM <=====[]=0
