### ISSUE TITLE
Close message in README.md

### ISSUE THREAD

**Issue by okapies** [lihaoyi/SprayWebSockets#8]
_README.md_ describes how to ["Close the Connection"](../blob/90fa58c0f95ec1aebe0d5b128ac300a950562b08/README.md#close-the-connection) but `SocketServer.Close` and `SocketServer.Closed` seem to incorrect. (`Tcp.Close` and `Tcp.Closed`?)

**Comment by lihaoyi** [comment]
Ah, looks like it's leftover from when it was relying on the milestone version of Spray, and the API has changed. Feel free to send a PR to fix it =)
